import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Graph from "~/components/Graph";
import MultiLineGraph from "~/components/Multigraph";
import HighMultiLine from "~/components/HighMultiLine"



export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });


  return (
    <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
{/* <MultiLineGraph></MultiLineGraph> */}
{/* <HighMultiLine></HighMultiLine> */}
          <Graph ></Graph>
        </div>
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          watch yo Data
        </h1>
    </main>
  </>
  );
}
